### ISSUE TITLE
How about adding `--co` options to add the `Co-authored-by:` trailer when committing?

### ISSUE THREAD

**Issue by aleen42** [gitgitgadget/git#1201] opened 2022-04-01 07:55 UTC
Prior art: https://github.com/nagoya-foundation/co-authored-commit

**Comment by phil-blain** [comment] 2022-04-01 11:23
This is a duplicate of https://github.com/gitgitgadget/git/issues/343. The Git maintainer explained in the message linked therein that they do not feel its reasonable to add a separate flag for every trailer a specific project could use.

A more general option `--trailer` was added in [that thread on the Git mailing list](https://lore.kernel.org/git/pull.901.git.1615446968597.gitgitgadget@gmail.com/t/#u), which came out in Git 2.32.0: https://github.com/gitgitgadget/git/blob/4b6846d9dcd391164b72bd70e8a0c0e09776afe3/Documentation/RelNotes/2.32.0.txt#L55-L57

With this option you can do:

```bash
git commit --trailer "Co-authored-by: Jane Doe <their.email@domain.com>"
```

You can also setup a [config variable](https://git-scm.com/docs/git-interpret-trailers#Documentation/git-interpret-trailers.txt-trailerlttokengtkey) to make it easier:
```bash
git config --global trailer.co.key "Co-authored-by"
git commit --trailer=co:"Jane Doe <their.email@domain.com>"
```

If your co-author has already authored some commits in the project's history, or you have another automated way to get their full name and email (LDAP for example), you can [make that even shorter](https://git-scm.com/docs/git-interpret-trailers#Documentation/git-interpret-trailers.txt-trailerlttokengtcmd):
```bash
git config --global trailer.co.key "Co-authored-by"
git config --global alias.who = '!f () { git --no-pager -c mailmap.blob=origin/master:.mailmap log -1 --format="%aN <%aE>" --author="$1" -i origin/master;  }; f'
git config --global trailer.co.cmd "git who"
git commit --trailer=co:jane
```

**Closed** 2022-04-01 12:00 UTC

**Comment by phil-blain** [comment] 2022-04-05 16:42
For lurkers, here is how I made it work with LDAP:
~~~bash
$ git config --global alias.ldap '!f() { result=$(ldapsearch -xLLL "(|(cn=*$1*)(uid=$1))"); name=$(printf "$result" | \grep ^cn | awk -F": " "{print \$2}"); mail=$(printf "$result" | \grep ^mail | awk -F": " "{print \$2}"); echo "$name <${mail,,}>"; }; f'
~~~

Here is what the function does in a more legible form:
~~~bash
f() { 
result=$(ldapsearch -xLLL "(|(cn=*$1*)(uid=$1))")
name=$(printf "$result" | \grep ^cn | awk -F': ' '{print $2}')
mail=$(printf "$result" | \grep ^mail | awk -F': ' '{print $2}')
echo "$name <${mail,,}>"
}
~~~

It uses `ldapsearch` to find people by their real names (first or last) or username. Using this as `trailer.*.cmd` assumes it yields a single result.
